#13
LiteLDev/docs pull request #16
Opened 2022-09-13 04:55 UTC by StarsDream00

2022-09-13 05:15 UTC, Futrime commented
Please describe what you have done in detail.

2022-09-13 05:16 UTC, StarsDream00 commented
> Please describe what you have done in detail.

it is writing

2022-09-13 06:13 UTC, Futrime requested changes
Thank you for your PR. Please make changes referring to my comments. DO NOT change the `cs`, `js`, `cpp` and `lua` language tags.

2022-09-13 06:13 UTC, Futrime commented on en/DotNETPluginDevelopment/APIs/Namespace/LLNET.AllowList/Class/AllowListManager/AllowListManager.md
> +```csharp
Please do not modify the language code, which conforms to the specifications of Prism.js and keeps a simple form.

2022-09-13 06:13 UTC, Futrime commented on en/LLSEPluginDevelopment/GameAPI/Command.md
> +[JavaScript]
Not beautiful.

2022-09-13 06:13 UTC, Futrime commented on en/Maintenance/StyleGuide.md
> +一般来说，每个 `.cpp` 文件都应该有一个同名的的 `.hpp` 文件。有一些常见的例外情况，如单元测试和只包含 `main()` 函数的小型 `.cpp` 文件。
DO NOT modify the style guide, which has been discussed by us LiteLDev, considering both the Google C++ Style Guide and the code already in LiteLoaderBDS.

2022-09-13 06:13 UTC, Futrime commented on en/Usage.md
> +There are 3 types of plugins: Native plugins, Script plugins and .NET plugins.
The .NET plugin belongs to the native plugin, also called LL plugin.

2022-09-13 06:13 UTC, Futrime commented on zh-Hans/_sidebar.md
> +- [⛳ 原生插件开发](https://cpp.docs.litebds.com/zh-Hans)
The C++ plugin does not equal to the native plugin.

2022-09-13 06:16 UTC, StarsDream00 commented on en/Usage.md
> +There are 3 types of plugins: Native plugins, Script plugins and .NET plugins.
.NET插件是由LL.NET加载的，运行机制及特性同步均与原生插件不同

2022-09-13 06:21 UTC, StarsDream00 commented on en/Usage.md
> +There are 3 types of plugins: Native plugins, Script plugins and .NET plugins.
并且LL缩写本身就带有歧义（整个 LiteLoaderBDS项目/LiteLoader原生插件加载部分/LiteLoader加载器公用API）

2022-09-13 06:26 UTC, StarsDream00 commented on en/Maintenance/StyleGuide.md
> +一般来说，每个 `.cpp` 文件都应该有一个同名的的 `.hpp` 文件。有一些常见的例外情况，如单元测试和只包含 `main()` 函数的小型 `.cpp` 文件。
现有的LiteLoaderBDS项目本就使用了.cpp/.hpp后缀，文档应以当前项目为准实时修改

2022-09-13 06:41 UTC, Futrime commented on en/Maintenance/StyleGuide.md
> +一般来说，每个 `.cpp` 文件都应该有一个同名的的 `.hpp` 文件。有一些常见的例外情况，如单元测试和只包含 `main()` 函数的小型 `.cpp` 文件。
The maintenance documentation is written for further development, including refactoring.

2022-09-13 06:44 UTC, Futrime commented on en/Usage.md
> +There are 3 types of plugins: Native plugins, Script plugins and .NET plugins.
Thanks for your hints. I feel quite sorry that not informing that .NET support is just under development, which should not be used in production environment and plugin development. I'm hiding these pages from the sidebar.

2022-09-14 00:26 UTC, Futrime requested changes

2022-09-14 00:26 UTC, Futrime commented on en/Usage.md
> +There are 3 types of plugins: Native plugins, Script plugins and .NET plugins.
Please remove the .NET plugin item.

2022-09-14 00:26 UTC, Futrime commented on zh-Hans/LLSEPluginDevelopment/DataAPI/PermAPI.md
> +和`Discord`一样，我们也有默认的`admin`(管理员)和`everyone`(所有人)身份组。
没必要改

2022-09-14 00:26 UTC, Futrime commented on zh-Hans/LLSEPluginDevelopment/EventAPI/EntityEvents.md
> +| Fire | 0x06 | 在火中烧死 |
Not died yet.

2022-09-14 00:26 UTC, Futrime commented on zh-Hans/LLSEPluginDevelopment/EventAPI/PlayerEvents.md
XUID

2022-09-14 07:56 UTC, Futrime approved these changes

2022-09-14 07:56 UTC, merged