Create LLSEJSPlugin.md
LiteLDev/docs pull request #5
Opened 2022-09-07 21:24 UTC by Colton1070

Creating a very simple guide for novice developers to help them get started developing JS scripts for LiteLoaderBDS. This page could be expanded to a full guide showing common methods and techniques (like config files, error handling, etc.) - things that are generally JS specific knowledge but have a strong use case for LiteLoaderBDS Development. I do not know Chinese so I will be unable to translate this file. I welcome modifications but the general purpose of the file should remain intact. This guide takes inspiration from Discord.js's Guide which can be found here for reference: https://discordjs.guide/#before-you-begin

2022-09-07 23:27 UTC, Futrime requested changes
You've done a good job! The docs are very close to perfect. Please modify some details based on my comments.

As for the Chinese translation problem, you needn't mind it. Just copy this file to the same place in /zh-Hans, I'm sure that someone will translate soon.

2022-09-07 23:27 UTC, Futrime commented on en/LLSEPluginDevelopment/ScriptAPI/LLSEJSPlugin.md
> +You will also need to set up a clean LiteLoaderBDS installation, details on how to install LiteLoaderBDS can be found [here](https://github.com/LiteLDev/LiteLoaderBDS#-install). This server will be u
Here you should write the link to the documentation (https://docs.litebds.com/en/#/Usage).

2022-09-07 23:27 UTC, Futrime commented on en/LLSEPluginDevelopment/ScriptAPI/LLSEJSPlugin.md
> +Before developing your first plugin, we will need to set up your developer environment (IDE). The choice of software you use to program is yours, but trusted and reliable software is recommended. [At
You can also recommend VSCode, another widely used editor.

2022-09-07 23:27 UTC, Futrime commented on en/LLSEPluginDevelopment/ScriptAPI/LLSEJSPlugin.md
> +## What do I do now?
Titles should be formatted. Refer to https://capitalizemytitle.com/

2022-09-08 00:29 UTC, Colton1070 commented
I had some issues navigating GitHub - I am still very new to repos. Hopefully the changes I made make sense. I have updated the page, moved it, and added it to the en sidebar. I noticed that the sidebar was linking parts of the docs:
- [📜 Using Javascript to Create Your First Plugin](/LLSEPluginDevelopment/LLSEJSPlugin.md)
Whereas in the LLSEJSPlugin.md, I used full links. Should I make another commit to change those links or is it ok?

2022-09-09 01:27 UTC, Futrime approved these changes
Good job.

2022-09-09 01:27 UTC, merged